"""
config — central settings and constants for CreatorPulse.

Typical usage:
    from config.settings import settings
    from config.constants import LogMsg, SourceStatus, Platform, Priority
"""
from config.settings import settings
from config.constants import (
    # Scoring weights
    WATCH_PERCENT_WEIGHT,
    DISCORD_WEIGHT,
    ENGAGEMENT_WEIGHT,
    # Thresholds
    RESONANCE_POOR_MAX,
    RESONANCE_AVERAGE_MAX,
    RESONANCE_STRONG_MAX,
    RESONANCE_VIRAL_MIN,
    MIN_WATCH_PERCENT,
    LOW_DISCORD_THRESHOLD,
    HIGH_VIEW_THRESHOLD,
    WATCH_PERCENT_DROP_THRESHOLD,
    # Community spike
    SPIKE_MULTIPLIER,
    COMMUNITY_BURST_LIMIT,
    SPIKE_WINDOW_HOURS,
    BASELINE_DAYS,
    # Growth prediction
    PREDICTION_DAYS,
    MIN_HISTORY_REQUIRED,
    TREND_WINDOW,
    CONFIDENCE_BAND_STD,
    # Cache
    CACHE_TTL,
    CACHE_MAX_SIZE,
    HACKATHON_CACHE_TTL,
    # Coral
    MAX_QUERY_ROWS,
    DEFAULT_TIMEFRAME_DAYS,
    CORAL_QUERY_TIMEOUT,
    CORAL_SCHEMA_CACHE_TTL_HOURS,
    # Timeframes
    TIMEFRAME_OPTIONS,
    DEFAULT_TIMEFRAME,
    TIMEFRAME_DAYS,
    # LLM
    MAX_CONTEXT_ROWS,
    MAX_RESPONSE_TOKENS,
    PROMPT_SUMMARY_LIMIT,
    NUM_RECOMMENDATIONS,
    # Retry
    MAX_API_RETRIES,
    RETRY_DELAY,
    CORAL_RETRY_LIMIT,
    LLM_OVERLOAD_RETRY_DELAY,
    # Paths
    MOCK_YOUTUBE_PATH,
    MOCK_DISCORD_PATH,
    MOCK_SHEETS_PATH,
    MOCK_INSIGHTS_PATH,
    MOCK_RESONANCE_PATH,
    CACHE_DIR,
    # Labels / helpers
    resonance_label,
    SourceStatus,
    SOURCE_HEALTH_STATUS,
    Priority,
    PRIORITY_ORDER,
    RECOMMENDATION_PRIORITIES,
    Platform,
    CORAL_TABLE_YOUTUBE,
    CORAL_TABLE_DISCORD,
    CORAL_TABLE_SHEETS,
    ALL_PLATFORMS,
    LogMsg,
    DEMO_QUESTIONS,
    RESONANCE_LABELS,
)

__all__ = [
    "settings",
    # weights
    "WATCH_PERCENT_WEIGHT", "DISCORD_WEIGHT", "ENGAGEMENT_WEIGHT",
    # thresholds
    "RESONANCE_POOR_MAX", "RESONANCE_AVERAGE_MAX", "RESONANCE_STRONG_MAX", "RESONANCE_VIRAL_MIN",
    "MIN_WATCH_PERCENT", "LOW_DISCORD_THRESHOLD", "HIGH_VIEW_THRESHOLD", "WATCH_PERCENT_DROP_THRESHOLD",
    # spike
    "SPIKE_MULTIPLIER", "COMMUNITY_BURST_LIMIT", "SPIKE_WINDOW_HOURS", "BASELINE_DAYS",
    # growth
    "PREDICTION_DAYS", "MIN_HISTORY_REQUIRED", "TREND_WINDOW", "CONFIDENCE_BAND_STD",
    # cache
    "CACHE_TTL", "CACHE_MAX_SIZE", "HACKATHON_CACHE_TTL",
    # coral
    "MAX_QUERY_ROWS", "DEFAULT_TIMEFRAME_DAYS", "CORAL_QUERY_TIMEOUT", "CORAL_SCHEMA_CACHE_TTL_HOURS",
    # timeframes
    "TIMEFRAME_OPTIONS", "DEFAULT_TIMEFRAME", "TIMEFRAME_DAYS",
    # llm
    "MAX_CONTEXT_ROWS", "MAX_RESPONSE_TOKENS", "PROMPT_SUMMARY_LIMIT", "NUM_RECOMMENDATIONS",
    # retry
    "MAX_API_RETRIES", "RETRY_DELAY", "CORAL_RETRY_LIMIT", "LLM_OVERLOAD_RETRY_DELAY",
    # paths
    "MOCK_YOUTUBE_PATH", "MOCK_DISCORD_PATH", "MOCK_SHEETS_PATH", "MOCK_INSIGHTS_PATH", "MOCK_RESONANCE_PATH", "CACHE_DIR",
    # labels / helpers
    "resonance_label", "SourceStatus", "SOURCE_HEALTH_STATUS",
    "Priority", "PRIORITY_ORDER", "RECOMMENDATION_PRIORITIES",
    "Platform", "CORAL_TABLE_YOUTUBE", "CORAL_TABLE_DISCORD", "CORAL_TABLE_SHEETS", "ALL_PLATFORMS",
    "LogMsg", "DEMO_QUESTIONS", "RESONANCE_LABELS",
]
